name: Bug report
description: Report a bug in Latch
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you do and what did you expect to happen?
      placeholder: Tell us what you saw.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Provide steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs (redact secrets).
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: Latch version / commit SHA (if known).
      placeholder: "0.1.0"
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS + Node version + Docker version (if relevant).
      placeholder: "macOS 14.x, Node 20.x, Docker Desktop 4.x"
    validations:
      required: false

